[package]
name = "zed_tutorial"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
mlua = { version = "0.10.2", features = ["lua54", "send"] }
notify = "7.0.0"
rand = "0.8.5"
regex = "1.11.1"
